name: Build binaries

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - 'doc/**'
      - 'docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Build binaries for linux-${{ matrix.target.GOARCH }}
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.target.container }}
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        target:
          - GOOS: linux
            GOARCH: amd64
            container: ubuntu:22.04

          - GOOS: linux
            GOARCH: arm64
            container: ubuntu:20.04

    steps:
      - name: Setup ubuntu container
        run: |
          apt update
          apt install -yqq build-essential make software-properties-common
          add-apt-repository -y ppa:git-core/candidate
          apt update && apt install -yqq git zip unzip zlib1g-dev zlib1g libzlcore-dev yasm

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.target.GOARCH }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.target.GOOS }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/github/home/compiled/lib/pkgconfig" >> $GITHUB_ENV
          echo "LP_BUILD_DIR=livepeer-${{ matrix.target.GOOS }}-${{ matrix.target.GOARCH }}" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir -p lp-builds/ releases/

      - name: Install dependencies
        run: |
          apt update \
            && apt install -yqq software-properties-common curl apt-transport-https lsb-release \
            && curl -fsSl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
            && add-apt-repository "deb https://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-14 main" \
            && apt update \
            && apt -yqq install \
              nasm clang-14 clang-tools-14 lld-14 build-essential pkg-config autoconf git python3 \
              crossbuild-essential-arm64 \
              golang-goprotobuf-dev protobuf-compiler-grpc

          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 30 \
            && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 30 \
            && update-alternatives --install /usr/bin/ld ld /usr/bin/lld-14 30

      - name: Install go modules
        if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install protoc plugins
        run: |
          GOARCH= GOOS= go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
          GOARCH= GOOS= go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

      - name: Install ffmpeg
        run: ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          ./ci_env.sh make

      - name: Archive binaries
        run: |
          mkdir -p "${GO_BUILD_DIR}/${LP_BUILD_DIR}/"
          cd "$GO_BUILD_DIR/"
          find . -type f -exec mv '{}' "$LP_BUILD_DIR" \;
          tar -czvf "../releases/$LP_BUILD_DIR.tar.gz" ./

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts-${{ matrix.target.GOOS }}-${{ matrix.target.GOARCH }}
          path: releases/

  macos-build:
    name: Build binaries for darwin-arm64
    runs-on: macos-arm64-self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "GOOS=darwin" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "LP_BUILD_DIR=livepeer-darwin-arm64" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir -p lp-builds/ releases/

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: ~/compiled
          key: ${{ runner.os }}-darwin-arm64-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}

      - name: Install dependencies
        run: |
          brew install coreutils pkgconf nasm || true

      - name: Install go modules
        run: go mod download

      - name: Install protoc plugins
        run: |
          GOARCH= GOOS= go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
          GOARCH= GOOS= go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          rm -rf ~/compiled ~/ffmpeg ~/x264 ~/nv-codec-headers
          ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          ./ci_env.sh make

      - name: Archive binaries
        run: |
          mkdir -p "${GO_BUILD_DIR}/${LP_BUILD_DIR}/"
          cd "$GO_BUILD_DIR/"
          find . -type f -exec mv '{}' "$LP_BUILD_DIR" \;
          tar -czvf "../releases/${LP_BUILD_DIR}.tar.gz" .

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts-darwin-arm64
          path: releases/
