name: Build binaries

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - 'doc/**'
      - 'docker/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Build binaries for ${{ matrix.target.GOOS }}-${{ matrix.target.type }}-${{ matrix.target.GOARCH }}
    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.target.container }}
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        target:
          - GOOS: linux
            GOARCH: amd64
            container: ubuntu:24.04
            type: cpu

          - GOOS: linux
            GOARCH: arm64
            container: ubuntu:24.04
            type: cpu

          - GOOS: linux
            GOARCH: amd64
            container: livepeerci/cuda:12.8.1-cudnn-devel-ubuntu24.04
            type: gpu

          - GOOS: linux
            GOARCH: arm64
            container: livepeerci/cuda:12.8.1-cudnn-devel-ubuntu24.04
            type: gpu

          - GOOS: windows
            GOARCH: amd64
            container: ubuntu:24.04
            type: cpu

    steps:
      - name: Setup ubuntu container
        run: |
          apt update
          apt install -yqq build-essential make software-properties-common curl
          add-apt-repository -y ppa:git-core/candidate
          apt update && apt install -yqq git zip unzip zlib1g-dev zlib1g libzlcore-dev yasm libva-dev

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.target.GOARCH }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.target.GOOS }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/compiled/lib/pkgconfig" >> $GITHUB_ENV
          echo "LP_BUILD_DIR=livepeer-${{ matrix.target.GOOS }}-${{ matrix.target.GOARCH }}" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir -p lp-builds/ releases/

      - name: Set GPU build environment
        if: matrix.target.type == 'gpu'
        run: |
          echo "CPATH=/usr/local/cuda_${{ matrix.target.GOARCH }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/cuda_${{ matrix.target.GOARCH }}/lib64" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/cuda_${{ matrix.target.GOARCH }}/lib64" >> $GITHUB_ENV
          echo "RELEASE_TAG=gpu" >> $GITHUB_ENV
          echo "LP_BUILD_DIR=livepeer-${{ matrix.target.GOOS }}-gpu-${{ matrix.target.GOARCH }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt update
          apt -yqq install \
            nasm clang-14 clang-tools-14 lld-14 build-essential pkg-config autoconf git python3 \
            cmake ninja-build meson \
            gcc-mingw-w64 g++-mingw-w64-x86-64 libgcc-14-dev-arm64-cross libstdc++-14-dev-arm64-cross \
            mingw-w64-tools gcc-mingw-w64-x86-64 mingw-w64-x86-64-dev \
            golang-goprotobuf-dev protobuf-compiler-grpc

          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 30 \
            && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 30 \
            && update-alternatives --install /usr/bin/ld ld /usr/bin/lld-14 30

      - name: Install go modules
        if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install protoc plugins
        run: |
          GOARCH= GOOS= go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
          GOARCH= GOOS= go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

      - name: Install zlib for windows
        if: matrix.target.GOOS == 'windows'
        env:
          CC: x86_64-w64-mingw32-gcc
        run: |
          apt install -yqq wget
          wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
          tar -xzf zlib-1.3.1.tar.gz
          cd zlib-1.3.1
          ./configure --prefix=/usr/x86_64-w64-mingw32 --static
          make
          make install

      - name: Install ffmpeg
        run: ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          ./ci_env.sh make

      - name: Archive binaries for windows
        if: matrix.target.GOOS == 'windows'
        run: |
          mkdir -p "${GO_BUILD_DIR}/${LP_BUILD_DIR}/"
          cd "$GO_BUILD_DIR/"
          find . -type f -exec mv '{}' "$LP_BUILD_DIR/" \;
          zip -9rq "../releases/$LP_BUILD_DIR.zip" ./

      - name: Archive binaries
        if: matrix.target.GOOS != 'windows'
        run: |
          mkdir -p "${GO_BUILD_DIR}/${LP_BUILD_DIR}/"
          cd "$GO_BUILD_DIR/"
          find . -type f -exec mv '{}' "$LP_BUILD_DIR" \;
          tar -czvf "../releases/$LP_BUILD_DIR.tar.gz" ./

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@v6
        with:
          name: release-artifacts-${{ matrix.target.GOOS }}-${{ matrix.target.type }}-${{ matrix.target.GOARCH }}
          path: releases/

  macos-build:
    name: Build binaries for darwin-arm64
    runs-on: macos-arm64-self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "GOOS=darwin" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "LP_BUILD_DIR=livepeer-darwin-arm64" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir -p lp-builds/ releases/

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: ~/compiled
          key: ${{ runner.os }}-darwin-arm64-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}

      - name: Install dependencies
        run: |
          eval "$(/opt/homebrew/bin/brew shellenv)"
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
          brew install coreutils pkgconf nasm cmake meson ninja || true

      - name: Install go modules
        # if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install protoc plugins
        run: |
          GOARCH= GOOS= go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
          GOARCH= GOOS= go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0

      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          rm -rf ~/compiled ~/ffmpeg ~/x264 ~/nv-codec-headers
          ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          ./ci_env.sh make

      - name: Archive binaries
        run: |
          mkdir -p "${GO_BUILD_DIR}/${LP_BUILD_DIR}/"
          cd "$GO_BUILD_DIR/"
          find . -type f -exec mv '{}' "$LP_BUILD_DIR" \;
          tar -czvf "../releases/${LP_BUILD_DIR}.tar.gz" .

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@v7
        with:
          name: release-artifacts-darwin-arm64
          path: releases/
