name: Create release

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download artifacts from build workflow
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: build.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: release-artifacts-.*
          name_is_regexp: true
          path: releases/

      - name: Flatten artifacts to single directory
        run: |
          cd releases/
          find . -type f -exec mv '{}' ./ \;
          find . -type d -empty -delete
          ls -la

      - name: Generate sha256 checksums
        run: |
          cd releases/
          sha256sum *.tar.gz > checksums.sha256
          cat checksums.sha256

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: |
            releases/*
